#!/bin/bash

while getopts d:s: flag
do
    case "${flag}" in
        d) devices=${OPTARG};;
	t) series=${OPTARG};;
    esac
done

echo "Devices: $devices";
echo "Test Series: $test-series";

appcenter test run espresso --app "project-rainbow/Project-Rainbow" --devices $devices --app-path android/app/build/outputs/apk/debug/app-debug.apk --test-series "$series" --locale "en_US" --build-dir android/app/build/outputs/apk/androidTest/debug/

